parameters:
  name: ''
  vmImage: ''
  toolchain: 'stable'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  variables:
    tc: ${{ parameters.toolchain }}
    os: ${{ parameters.vmImage }}
  steps: 
  - bash: |
      if [[ "$OS" == "xcode9-macos10.13" ]]; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew install libsodium
      fi
      if [[ "$OS" == "ubuntu-16.04" ]]; then
        sudo apt-get install libsodium-dev libssl1.0.0
      fi
    displayName: 'Install dependencies'

  - bash: |
      curl -o rustup-init.sh https://sh.rustup.rs -sSf
      sh rustup-init.sh --default-toolchain $(tc) -y
    displayName: 'Install Rust'

  - bash: |
      source $HOME/.cargo/env
      cargo build --all-features
    displayName: 'Build Serenity'

  - bash: |
      source $HOME/.cargo/env
      cargo test --all-features
    displayName: 'Test Serenity'
