parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  toolchain: 'stable'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  variables:
    tc: ${{ parameters.toolchain }}
    os: ${{ parameters.vmImage }}
  steps: 
  - bash: |
      if [[ "$OS" == "xcode9-macos10.13" ]]; then 
        brew install libsodium
      else
        git clone 'git://github.com/jedisct1/libsodium.git'
        cd libsodium
        ./autogen.sh
        ./configure && make
        sudo make install
      fi

  - bash: |
      curl -o rustup-init.sh https://sh.rustup.rs -sSf
      sh rustup-init.sh --default-toolchain $(tc) -y
    displayName: 'Install rust'

  - bash: |
      cd serenity
      source $HOME/.cargo/env
      cargo build --all-features
    displayName: 'Build serenity'

  - bash: |
      cd serenity
      source $HOME/.cargo/env
      cargo test --all-features
    displayName: 'Test serenity'